### ISSUE TITLE
New batch search error: see what it is and if we can increase transparency

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#578] opened 2020-08-04 08:18 UTC
**Is your feature request related to a problem? Please describe.**
The feature request is related to a new type of error that we see in batch searches. The error is "Data too large, data for [<http_request>] would be [14608155380/13.6gb], which is larger than the limit of [13716003225/12.7gb]". 

**Describe the solution you'd like**
I don't expect any solution at the moment but we said we would investigate this new type of error just to see what it means and depending on what we find, we will see if we can be more transparent with users about these errors.

**Comment by bamthomas** [comment] 2020-08-31 14:28
do you have an example (search query, batch search) ?

**Comment by Soliine** [comment] 2020-09-29 08:14
I sent an email (with an object containing "578") with examples to you and Maxime this morning.

**Comment by bamthomas** [comment] 2020-11-05 09:22
duplicate of #665 (there is the log there)

**Closed** 2020-11-05 09:21 UTC
Labels: back, enhancement
