### ISSUE TITLE
how do we change the IP/TCP port for datashare?

### ISSUE THREAD

**Issue by StoltHD** [ICIJ/datashare#266] opened 2019-10-11 11:54 UTC
only changing it in the .yml file doesn't work..

anyone with a solution for this, I can't run it on port 8080...

**Comment by bamthomas** [comment] 2019-10-11 13:06
duplicate of #265

**Closed by bamthomas** 2019-10-11 13:06 UTC

**Comment by Soliine** [comment] 2020-04-20 13:11
You can now change Datashare's settings here : http://localhost:8080/#/settings
