### ISSUE TITLE
Wrong language detection of PDFs if metadata language is wrong

### ISSUE THREAD

**Issue by kaerumy** [ICIJ/datashare#781] opened 2021-03-25 10:23 UTC
**Describe the bug**

If creator metadata is English (en_US etc.) but document text is actually in another language or script, the main language is set as English even if most of the text is in another language.

**To Reproduce**
1. Upload Burmese PDF for which the original creator metadata languge is set to en_us
2. Analyse Document -> Extract Text
3. Document is tagged as English, despite almost all of the text being in another language

**Expected behavior**
Actual text of PDF is analysed and main language of actual text tagged. If possible, set multiple language tags see #309 

**Screenshots**

![image](https://user-images.githubusercontent.com/1060743/112457565-dac6bb00-8d96-11eb-92b4-425b4e6918f8.png)

![image](https://user-images.githubusercontent.com/1060743/112457643-eade9a80-8d96-11eb-8aff-0f4ab7735a82.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Chrome
 - Version: 89.0.4389.90 (Official Build) 

**Additional context**
File attached:

[8f79262d-9a5a-47e6-b931-f1711dda88a6.pdf](https://github.com/ICIJ/datashare/files/6203903/8f79262d-9a5a-47e6-b931-f1711dda88a6.pdf)

**Comment by pirhoo** [comment] 2022-09-02 16:11
This is actually a feature, not a bug. When starting the extraction, Datashare tries to guess the language using whatever information it has.

Closing in favor https://github.com/ICIJ/datashare/issues/938

**Closed by pirhoo** 2022-09-02 16:11 UTC
Labels: enhancement, full stack
