### ISSUE TITLE
When launched manually from the server, indexation/extraction process should close out when finished 

### ISSUE THREAD

**Issue by madoleary** [ICIJ/datashare#743] opened 2021-02-01 15:49 UTC
**Describe the bug**
After manually launching an extraction queue from the server, the process should automatically close-out when finished. Instead, it stays running, even if the process completed successfully, so that the user must type `ctrl + C` to end it.

**Comment by bamthomas** [comment] 2021-03-05 11:22
If I remember well, the use case was the following : 

- we added manually a path into the index queue
- we executed the INDEX stage alone (without SCAN)
- the index did not stopped

What could be the cause of process that did not stop was maybe the fact that we did not add the [poison pill](https://java-design-patterns.com/patterns/poison-pill/)

**Comment by Soliine** [comment] 2021-09-14 14:40
We were waiting for the poison pill to close the consumer but now it should be fixed.

**Closed by Soliine** 2021-09-14 14:40 UTC
Labels: back
