### ISSUE TITLE
Can't index a .ods document on a Lenovo Thinkpad

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#610] opened 2020-08-31 10:35 UTC
**Describe the bug**
A user cannot index a .ods (OpenDocument Spreadsheet) on their machine using Datashare 7.6.0. The size of the document is 471 559 bytes (475 KB on disk). (Github doesn't support that file type but I can send the document to you)

**To Reproduce**
1. The user uses a Lenovo Thinkpad with Windows 10 Pro, 18362.1016.1. Version 1903, installed in December 2019. 
2. They have these logs:
_2020-08-28 12:25:29,301 [main] INFO  Main - Running datashare web server
2020-08-28 12:25:29,313 [main] WARN  PropertiesProvider - no C:\Users\xxx\AppData\Roaming\Datashare\dist\datashare.conf file found, using default values
2020-08-28 12:25:29,376 [main] INFO  PropertiesProvider - adding properties from env vars {}
2020-08-28 12:25:29,376 [main] INFO  PropertiesProvider - properties set to {}
2020-08-28 12:25:29,376 [main] INFO  PropertiesProvider - merged properties (without override) with {tcpListenPort=8080, scrollSize=1000, elasticsearchAddress=http://elasticsearch:9200, queueName=extract:queue, browserOpenLink=true, sessionTtlSeconds=43200, scrollSlices=1, queueType=memory, filterSet=extract:filter, protectedUriPrefix=/api/, cors=no-cors, mode=EMBEDDED, redisPoolSize=1, redisAddress=redis://redis:6379, defaultUserName=local, ocr=true, nlpParallelism=1, parserParallelism=1, dataSourceUrl=jdbc:sqlite:file:C:\Users\xxxx\AppData\Roaming\Datashare\dist\datashare.db, defaultProject=local-datashare, elasticsearchDataPath=C:\Users\xxxx\AppData\Roaming\Datashare\index, dataDir=C:\Users\xxxx\AppData\Roaming\Datashare\data, settings=C:\Users\xxxx\AppData\Roaming\Datashare\dist\datashare.conf, clusterName=datashare, busType=memory, messageBusAddress=redis, parallelism=4}
2020-08-28 12:25:29,884 [Thread-0] INFO  NodeEnvironment - using [1] data paths, mounts [[Windows (C:)]], net usable_space [102.5gb], net total_space [237.2gb], types [NTFS]
2020-08-28 12:25:29,897 [Thread-0] INFO  NodeEnvironment - heap size [1.7gb], compressed ordinary object pointers [true]
2020-08-28 12:25:29,913 [Thread-0] INFO  Node - node name derived from node ID [kY3YaVo0TVGMF0z790J4Ww]; set [node.name] to override
2020-08-28 12:25:29,914 [Thread-0] INFO  Node - version[6.5.4-SNAPSHOT], pid[2564], build[unknown/unknown/Unknown/Unknown], OS[Windows 10/10.0/amd64], JVM[/OpenJDK 64-Bit Server VM/1.8.0_242/25.242-b08]
2020-08-28 12:25:29,914 [Thread-0] INFO  Node - JVM arguments [-DPROD_MODE=true, -Djava.system.class.loader=org.icij.datashare.DynamicClassLoader]
2020-08-28 12:25:29,914 [Thread-0] WARN  Node - version [6.5.4-SNAPSHOT] is a pre-release version of Elasticsearch and is not suitable for production
2020-08-28 12:25:30,064 [Thread-0] INFO  PluginsService - no modules loaded
2020-08-28 12:25:30,065 [Thread-0] INFO  PluginsService - loaded plugin [org.elasticsearch.analysis.common.CommonAnalysisPlugin]
2020-08-28 12:25:30,066 [Thread-0] INFO  PluginsService - loaded plugin [org.elasticsearch.index.reindex.ReindexPlugin]
2020-08-28 12:25:30,066 [Thread-0] INFO  PluginsService - loaded plugin [org.elasticsearch.join.ParentJoinPlugin]
2020-08-28 12:25:30,066 [Thread-0] INFO  PluginsService - loaded plugin [org.elasticsearch.painless.PainlessPlugin]
2020-08-28 12:25:30,067 [Thread-0] INFO  PluginsService - loaded plugin [org.elasticsearch.transport.Netty4Plugin]
2020-08-28 12:25:36,254 [Thread-0] INFO  DiscoveryModule - using discovery type [zen] and host providers [settings]
2020-08-28 12:25:36,828 [Thread-0] INFO  Node - initialized
2020-08-28 12:25:36,829 [Thread-0] INFO  Node - starting ...
2020-08-28 12:25:39,050 [Thread-0] INFO  TransportService - publish_address {127.0.0.1:9300}, bound_addresses {127.0.0.1:9300}, {[::1]:9300}
2020-08-28 12:25:42,141 [elasticsearch[kY3YaVo][masterService#updateTask][T#1]] INFO  MasterService - zen-disco-elected-as-master ([0] nodes joined), reason: new_master {kY3YaVo}{kY3YaVo0TVGMF0z790J4Ww}{Smo4AlUrTxmqBjc0-1_gSw}{127.0.0.1}{127.0.0.1:9300}
2020-08-28 12:25:42,148 [elasticsearch[kY3YaVo][clusterApplierService#updateTask][T#1]] INFO  ClusterApplierService - new_master {kY3YaVo}{kY3YaVo0TVGMF0z790J4Ww}{Smo4AlUrTxmqBjc0-1_gSw}{127.0.0.1}{127.0.0.1:9300}, reason: apply cluster state (from master [master {kY3YaVo}{kY3YaVo0TVGMF0z790J4Ww}{Smo4AlUrTxmqBjc0-1_gSw}{127.0.0.1}{127.0.0.1:9300} committed version [1] source [zen-disco-elected-as-master ([0] nodes joined)]])
2020-08-28 12:25:42,484 [elasticsearch[kY3YaVo][masterService#updateTask][T#1]] INFO  GatewayService - recovered [1] indices into cluster_state
2020-08-28 12:25:42,940 [elasticsearch[kY3YaVo][masterService#updateTask][T#1]] INFO  AllocationService - Cluster health status changed from [RED] to [YELLOW] (reason: [shards started [[local-datashare][0]] ...]).
2020-08-28 12:25:43,240 [Thread-0] INFO  Netty4HttpServerTransport - publish_address {127.0.0.1:9200}, bound_addresses {127.0.0.1:9200}, {[::1]:9200}
2020-08-28 12:25:43,241 [Thread-0] INFO  Node - started
2020-08-28 12:25:43,243 [Thread-0] INFO  PropertiesProvider - overriding properties with {elasticsearchAddress=http://localhost:9200}
2020-08-28 12:25:43,655 [Thread-0] INFO  EmbeddedMode - plugin dir not found invalid path for plugins: .\extensions
2020-08-28 12:25:43,678 [Thread-0] INFO  HikariDataSource - HikariPool-1 - Starting...
2020-08-28 12:25:43,767 [Thread-0] INFO  HikariDataSource - HikariPool-1 - Start completed.
2020-08-28 12:25:43,794 [Thread-0] INFO  HikariDataSource - HikariPool-2 - Starting...
2020-08-28 12:25:43,796 [Thread-0] INFO  HikariDataSource - HikariPool-2 - Start completed.
2020-08-28 12:25:43,806 [Thread-0] INFO  HikariDataSource - HikariPool-3 - Starting...
2020-08-28 12:25:43,810 [Thread-0] INFO  HikariDataSource - HikariPool-3 - Start completed.
2020-08-28 12:25:44,138 [Thread-0] INFO  HikariDataSource - HikariPool-4 - Starting...
2020-08-28 12:25:44,141 [Thread-0] INFO  HikariDataSource - HikariPool-4 - Start completed.
2020-08-28 12:25:49,736 [Thread-0] INFO  JdbcExecutor - SELECT COUNT(*) FROM DATABASECHANGELOGLOCK
2020-08-28 12:25:49,746 [Thread-0] INFO  JdbcExecutor - SELECT COUNT(*) FROM DATABASECHANGELOGLOCK
2020-08-28 12:25:49,751 [Thread-0] INFO  JdbcExecutor - SELECT LOCKED FROM DATABASECHANGELOGLOCK WHERE ID=1
2020-08-28 12:25:49,780 [Thread-0] INFO  StandardLockService - Successfully acquired change log lock
2020-08-28 12:25:51,007 [Thread-0] INFO  JdbcExecutor - SELECT MD5SUM FROM DATABASECHANGELOG WHERE MD5SUM IS NOT NULL
2020-08-28 12:25:51,012 [Thread-0] INFO  JdbcExecutor - SELECT COUNT(*) FROM DATABASECHANGELOG
2020-08-28 12:25:51,013 [Thread-0] INFO  StandardChangeLogHistoryService - Reading from DATABASECHANGELOG
2020-08-28 12:25:51,015 [Thread-0] INFO  JdbcExecutor - SELECT * FROM DATABASECHANGELOG ORDER BY DATEEXECUTED ASC, ORDEREXECUTED ASC
2020-08-28 12:25:51,139 [Thread-0] INFO  StandardLockService - Successfully released change log lock
2020-08-28 12:25:51,141 [Thread-0] INFO  HikariDataSource - HikariPool-4 - Shutdown initiated...
2020-08-28 12:25:51,153 [Thread-0] INFO  HikariDataSource - HikariPool-4 - Shutdown completed.
2020-08-28 12:25:51,888 [Thread-0] INFO  Indexer - indexer defined with cfg{indexType='doc', indexJoinField='join', docTypeField='type', shards=1, replicas=1}
2020-08-28 12:25:52,264 [pool-3-thread-1] INFO  IndexWaiterFilter - Ping elasticsearch succeeded
2020-08-28 12:25:52,870 [Thread-0] INFO  Fluent - Production mode
2020-08-28 12:25:52,906 [Thread-0] INFO  Fluent - Server started on port 8080
2020-08-28 12:26:00,410 [Worker: RequestDispatcher: Thread-12] INFO  ScanIndexTask - scanning index local-datashare with scroll size 1000 and 1 slices
2020-08-28 12:26:00,416 [pool-2-thread-1] INFO  Scanner - Queuing scan of: "C:\Users\xxxx\AppData\Roaming\Datashare\data".
2020-08-28 12:26:00,418 [pool-2-thread-1] INFO  ScannerVisitor - Starting scan of: "C:\Users\xxxx\AppData\Roaming\Datashare\data".
2020-08-28 12:26:00,426 [pool-2-thread-1] INFO  ScannerVisitor - Entering directory: "C:\Users\xxxx\AppData\Roaming\Datashare\data".
2020-08-28 12:26:00,428 [pool-2-thread-1] INFO  ScannerVisitor - Completed scan of: "C:\Users\xxxx\AppData\Roaming\Datashare\data".
2020-08-28 12:26:00,628 [Worker: RequestDispatcher: Thread-12] INFO  ScanIndexTask - imported 2 paths into {C:\Users\xxxx\AppData\Roaming\Datashare\data\deliberations-du-conseil-municipal-de-toulouse-a-partir-davril-2014.ods=org.icij.extract.report.Report@f931e6c}
2020-08-28 12:26:01,573 [Worker: RequestDispatcher: Thread-12] INFO  ElasticsearchSpewer - spewer defined with cfg{indexType='doc', indexJoinField='join', docTypeField='type', shards=1, replicas=1}
2020-08-28 12:26:02,111 [Worker: RequestDispatcher: Thread-12] INFO  IndexTask - {tcpListenPort=8080, scrollSize=1000, elasticsearchAddress=http://localhost:9200, queueName=extract:queue, browserOpenLink=true, sessionTtlSeconds=43200, scrollSlices=1, queueType=memory, filterSet=extract:filter, filter=true, protectedUriPrefix=/api/, cors=no-cors, mode=EMBEDDED, redisPoolSize=1, redisAddress=redis://redis:6379, defaultUserName=local, ocr=false, nlpParallelism=1, parserParallelism=1, dataSourceUrl=jdbc:sqlite:file:C:\Users\xxxx\AppData\Roaming\Datashare\dist\datashare.db, reportName=extract:report, settings=C:\Users\xxxx\AppData\Roaming\Datashare\dist\datashare.conf, dataDir=C:\Users\xxxx\AppData\Roaming\Datashare\data, elasticsearchDataPath=C:\Users\xxxx\AppData\Roaming\Datashare\index, defaultProject=local-datashare, messageBusAddress=redis, busType=memory, clusterName=datashare, parallelism=4}
2020-08-28 12:26:02,111 [Worker: RequestDispatcher: Thread-12] INFO  IndexTask - disable OCR
2020-08-28 12:26:02,118 [Worker: RequestDispatcher: Thread-12] INFO  IndexTask - report map enabled with name set to extract:report
2020-08-28 12:26:02,121 [pool-2-thread-2] INFO  IndexTask - Processing up to 4 file(s) in parallel
2020-08-28 12:26:02,124 [pool-6-thread-1] INFO  DocumentQueueDrainer - Draining to consumer until stopped or interrupted.
2020-08-28 12:26:02,125 [pool-6-thread-1] INFO  DocumentConsumer - Sending to thread pool; will queue if full: "C:\Users\xxxx\AppData\Roaming\Datashare\data\deliberations-du-conseil-municipal-de-toulouse-a-partir-davril-2014.ods".
2020-08-28 12:26:02,128 [pool-6-thread-1] INFO  DocumentQueueDrainer - Continuous draining stopped.
2020-08-28 12:26:02,130 [pool-2-thread-2] INFO  DocumentQueueDrainer - Shutting down.
2020-08-28 12:26:02,131 [pool-2-thread-2] INFO  DocumentQueueDrainer - Awaiting completion up to 10 SECONDS.
2020-08-28 12:26:02,131 [pool-2-thread-2] INFO  DocumentQueueDrainer - Terminated.
2020-08-28 12:26:02,132 [pool-5-thread-1] INFO  DocumentConsumer - Beginning extraction: "C:\Users\xxxx\AppData\Roaming\Datashare\data\deliberations-du-conseil-municipal-de-toulouse-a-partir-davril-2014.ods".
2020-08-28 12:26:02,132 [pool-2-thread-2] INFO  IndexTask - drained 1 documents. Waiting for consumer to shutdown
2020-08-28 12:26:02,134 [pool-5-thread-1] INFO  Extractor - File already extracted; skipping: "C:\Users\xxxx\AppData\Roaming\Datashare\data\deliberations-du-conseil-municipal-de-toulouse-a-partir-davril-2014.ods".
2020-08-28 12:26:02,139 [pool-2-thread-2] INFO  DocumentConsumer - Shutting down.
2020-08-28 12:26:02,140 [pool-2-thread-2] INFO  DocumentConsumer - Awaiting completion up to 30 MINUTES.
2020-08-28 12:26:02,141 [pool-2-thread-2] INFO  DocumentConsumer - Terminated.
2020-08-28 12:26:02,142 [pool-2-thread-2] INFO  IndexTask - exiting_

**Expected behavior**
We expect the document to be indexed. The user sent the document to me and I could index it properly on my MacBookPro Catalina 10.15.6 using Chrome.

<img width="1378" alt="Screenshot 2020-08-31 at 12 33 32" src="https://user-images.githubusercontent.com/17233829/91711552-5e645480-eb86-11ea-8263-b749b8a3829d.png">

**Desktop:**
 - OS: Lenovo Thinkpad with Windows 10 Pro, 18362.1016.1
 - Browser: unknown
 - Version: Version 1903

**Comment by bamthomas** [comment] 2021-03-05 14:15
can't reproduce this issue, I indexed several ODS files and it went well. 

The traces show that the file has already be indexed.
I'm closing and we can reopen if we find other cases.

**Closed by bamthomas** 2021-03-05 14:15 UTC
Labels: back, bug
