### ISSUE TITLE
ERROR CoreNlpNerModels - failed loading NER java.io.IOException

### ISSUE THREAD

**Issue by TomElRumi** [ICIJ/datashare#532] opened 2020-06-01 06:10 UTC
Hi there, started getting the below error when trying to run the CoreNLP model and the process gets stuck at 99%. Anything I can do differently to make this work? Was working fine until Saturday or so...

2020-05-31 23:29:26,960 [CORENLP-0] ERROR CoreNlpNerModels - failed loading NER
java.io.IOException: Unable to open "edu/stanford/nlp/models/ner/english.all.3class.distsim.crf.ser.gz" as class path, filename or URL
	at edu.stanford.nlp.io.IOUtils.getInputStreamFromURLOrClasspathOrFileSystem(IOUtils.java:480)
	at edu.stanford.nlp.ie.AbstractSequenceClassifier.loadClassifier(AbstractSequenceClassifier.java:1503)
	at edu.stanford.nlp.ie.AbstractSequenceClassifier.loadClassifier(AbstractSequenceClassifier.java:1495)
	at edu.stanford.nlp.ie.crf.CRFClassifier.getClassifier(CRFClassifier.java:2932)
	at org.icij.datashare.text.nlp.corenlp.models.CoreNlpNerModels.loadModelFile(CoreNlpNerModels.java:75)
	at org.icij.datashare.text.nlp.corenlp.models.CoreNlpNerModels.loadModelFile(CoreNlpNerModels.java:39)
	at org.icij.datashare.text.nlp.AbstractModels.load(AbstractModels.java:59)
	at org.icij.datashare.text.nlp.AbstractModels.get(AbstractModels.java:46)
	at org.icij.datashare.text.nlp.corenlp.CorenlpPipeline.processNerClassifier(CorenlpPipeline.java:196)
	at org.icij.datashare.text.nlp.corenlp.CorenlpPipeline.process(CorenlpPipeline.java:91)
	at org.icij.datashare.nlp.NlpConsumer.findNamedEntities(NlpConsumer.java:73)
	at org.icij.datashare.nlp.NlpConsumer.call(NlpConsumer.java:43)
	at org.icij.datashare.nlp.NlpConsumer.call(NlpConsumer.java:20)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2020-05-31 23:29:26,960 [CORENLP-0] WARN  NlpConsumer - error in consumer main loop
java.lang.NullPointerException: null
	at org.icij.datashare.text.nlp.corenlp.CorenlpPipeline.processNerClassifier(CorenlpPipeline.java:197)
	at org.icij.datashare.text.nlp.corenlp.CorenlpPipeline.process(CorenlpPipeline.java:91)
	at org.icij.datashare.nlp.NlpConsumer.findNamedEntities(NlpConsumer.java:73)
	at org.icij.datashare.nlp.NlpConsumer.call(NlpConsumer.java:43)
	at org.icij.datashare.nlp.NlpConsumer.call(NlpConsumer.java:20)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by bamthomas** [comment] 2020-06-02 09:16
yes we are on it, it seems we have a regression since we made changes to load plugins.

This is duplicate of #497

**Closed by bamthomas** 2020-06-02 09:16 UTC

**Comment by bamthomas** [comment] 2020-06-03 15:10
@TomElRumi you can ckeck the 7.0.2 that should fix your issue
