### ISSUE TITLE
"Term1 AND Term2": if I delete Term1, search query is wrong

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#280] opened 2019-10-15 14:19 UTC
The query becomes "AND Term2" and then it is wrong. Do we want to correct this bug?

**Comment by annelhote** [comment] 2019-10-28 16:37
Oops, can't reproduce it in prod. @Soliine can you ? If not, let's close this issue...

**Comment by Soliine** [comment] 2019-10-31 13:32
I can't reproduce it now... I tested with different terms in different projects with operators AND and NOT, in the server and in local DS. Should we close the issue?

**Closed** 2019-11-04 16:02 UTC
Labels: bug, front, question
